### PR TITLE
Generate a version that's compatible with vanilla Node

### PR DESCRIPTION
**Pull request by bebraw**
Now there's `dist-modules` that contains a vanilla version (JSX expanded, no ES6 etc.). It simply runs babel when you hit `npm run dist`. `package.json` main fields points at this version making it easy to consume the library from Node.

Note that I loosened `peerDependencies` version requirement while at it. It's easy to end up in a situation where a library would work in some future version but too strict peer dependency doesn't allow this.

If you want I can set up a Webpack based distribution build for you in a separate PR.

### CODE REVIEW

**Comment by Yomguithereal** [comment]
What I don't get here @bebraw is how you will require the strategies independently now? What I'd like to avoid is for one to load unnecessary files when choosing a strategy.

**Comment by bebraw** [comment]
@Yomguithereal Good point. I expect tooling can take care of that (ie. eliminate dead code). In Node context you could refer directly to some file (say `require('baobab-react/mixin')`). That wouldn't hit `index.js` and load rest of the code then for sure.

If you want, we can create separate distribution bundles for each strategy for other environments.

**Comment by Yomguithereal** [comment]
What I initially understood is that there were no building required is this case.

If you `require('baobab-react/mixins'));` for the time being, only ES5 files are loaded, so no building required.

Only the higher-order have ES6 files and if you use them, you are effectively using ES6 and probably babel to build them so the files will be built along with yours, no?

**Comment by bebraw** [comment]
> Only the higher-order have ES6 files and if you use them, you are effectively using ES6 and probably babel to build them so the files will be built along with yours, no?

It's easier to consume when they are in JS format (hence `dist-modules`) (no extra configuration needed) but I can solve this on my end if needed.

**Comment by Yomguithereal** [comment]
I think I do not know all the potential use cases: is this possible you'll use HOC in ES5 code, for instance? If this is the case then yes it would make sense to build the files here. 

One solution could be to let the root files like `higher-order.js` require the built files.

**Comment by bebraw** [comment]
> Is this possible you'll use HOC in ES5 code, for instance? 

I've moved onto ES6 env (Webpack powered) but that doesn't mean someone couldn't find it useful.

> One solution could be to let the root files like higher-order.js require the built files.

What would that look like from Node? It's enough if you can do just `require('baobab-react/hoc')` etc. Those will point at built versions (easier to consume).

**Comment by Yomguithereal** [comment]
`./higher-order.js` would look like

```js
module.exports = require('./dist-modules/higher-order.js');
```

**Comment by bebraw** [comment]
Alright. If I can do `require('baobab-react/higher-order')` and have it resolved to a `dist-module` version like that, it's enough.

**Comment by Yomguithereal** [comment]
Ok. Let's do that then :) .

**Comment by bebraw** [comment]
@Yomguithereal I added the wrappers to project root and made sure the imports work. Now it works as discussed.

**Pull request merged**
