### PR TITLE
Create .babelrc

### PR DESCRIPTION
**Pull request by szhigunov**

### CODE REVIEW

**Comment by Yomguithereal** [comment]
Hello @szhigunov. Why do you need to add a `.babelrc` file? The babel config is already in the package.json [here](https://github.com/Yomguithereal/baobab-react/blob/master/package.json#L50-L56).

**Comment by szhigunov** [comment]
Its a necessary part to add support react-native. React-native inspect all
deps and assumes that we need to use babel presets in applications, so
better way is to move babel config from package.json. That problem is also
touches in issue 102.

**Comment by Yomguithereal** [comment]
Thanks @szhigunov. Your PR is already merged and released in v2.1.2.

**Comment by szhigunov** [comment]
Already using in our application! Thanks

**Pull request merged**
