### PR TITLE
Prevent re-renders when using branch

### PR DESCRIPTION
**Pull request by ConradIrwin**
Before this change, the ComposedComponent returned by branch() would
call setState() in componentDidMount and (if the mapping changed)
componentDidUpdate.

The setState in componentDidMount was mostly unnoticable, but does cause
a small slowdown. The componentDidUpdate behaviour was more broken as
when a ComposedComponent's props changed it would first render its child
components with the new props but the tree state returned by watching
the mapping from the previous props. In componentDidUpdate it would then
correct the mapping and render the child component a second time (this
time correctly) with the new props and tree state returned by watching
the new props.

After this change, we use React's new `calculateDerivedStateFromProps`
to ensure that the child component is rendered once on mount and update;
and that the props are always up to date with the mapping.

### CODE REVIEW

**Comment by Yomguithereal** [comment]
Hello @ConradIrwin. Thanks for the PR. I'll trust you on it since I has been a long time since I last used React. Do you think this can safely be a `4.0.2`? Or should I bump minor or major?

**Comment by ConradIrwin** [comment]
@Yomguithereal I think this is fine to be in `4.0.2` as it's a bug fix for a regression in `4.0.0`.

We should probably give @soulprovidr  a heads-up as at least one known user of the new code :D.

Thanks again for creating baobab, it's a great abstraction.

**Comment by Yomguithereal** [comment]
Let's go then :)

**Comment by Yomguithereal** [comment]
4.0.2 is live on npm

**Comment by ConradIrwin** [comment]
Thanks!

**Comment by mattzeunert** [comment]
Thanks a lot for fixing this @ConradIrwin! Was surprised to see my component rerendering with old data, but now it's fixed after upgrading 👍

**Pull request merged**
